### ISSUE TITLE
bob.io.base.test_file.test_peek segfaults with error 11

### ISSUE THREAD

**Issue by 183amir** [bioidiap/bob.io.base#10]
The full log is available here (https://travis-ci.org/conda-forge/staged-recipes/jobs/122066381). Note that this happens only on Mac OSX.

**Comment by tiagofrepereira2012** [comment]
Well, just to keep track on this I have been debugging in the my laptop.

The segfault happens right after the return of the PyBobIoFile_New function for non reason.
I found a similar issue here https://github.com/esheldon/esutil/issues/12
Anyways, I'm still on it

Cheers

**Comment by tiagofrepereira2012** [comment]
Hey, I'm just going back to this issue.

I managed to build bob.io.base using my miniconda, but now I have a different issue.
When I try to import the bob.io.base I got the following thing

```
File "/Users/tiagodefreitaspereira/Documents/buildOutProjects/bioidiap/bob.io.base/bob/io/base/__init__.py", line 8, in <module>
    from ._library import File, HDF5File, extensions
ImportError: dlopen(/Users/tiagodefreitaspereira/Documents/buildOutProjects/bioidiap/bob.io.base/bob/io/base/_library.so, 2): Symbol not found: __ZN3bob2io4base6detail4hdf55GroupixERKSs
  Referenced from: /Users/tiagodefreitaspereira/Documents/buildOutProjects/bioidiap/bob.io.base/bob/io/base/_library.so
  Expected in: dynamic lookup
```
I'm a little bit confused.
The undefined symbols is this one `bob::io::base::detail::hdf5::Group::operator[](std::string const&)`,
which is defined here https://github.com/bioidiap/bob.io.base/blob/master/bob/io/base/cpp/HDF5Group.cpp#L223

What is going on?

**Comment by 183amir** [comment]
This is some compiler issue that I have seen before. Try using either `libc++` or `libstd++` in your compilation flags or `clang` or `gcc`. Either way, could you share what you have done so far?

**Comment by tiagofrepereira2012** [comment]
Hey, just some links to keep tracking tomorrow.

libc++ is the default after Maverics, so we don't need to set it
  http://stackoverflow.com/questions/19774778/when-is-it-necessary-to-use-use-the-flag-stdlib-libstdc

Adding -std=libstd++ when you use clang++ make it compiles, but it crashes in segmentation fault.
Although they are API comparible they are not ABI compatible. In the end the binary code mess up with the reference counters; specially when you deal with std::string, which is exactly happening. So this is not the way to go:
 http://stackoverflow.com/questions/12542971/using-libstdc-compiled-libraries-with-clang-stdlib-libc
  https://trac.macports.org/ticket/40925

I still didn't manage to solve the thing on conda, but this direction seems one possibility to solve

https://github.com/nodejs/node-gyp/issues/469

**Comment by tiagofrepereira2012** [comment]
Solved the linking problem adding the environment variable `export MACOSX_DEPLOYMENT_TARGET=10.9`

Suggested here:

https://github.com/rootpy/root_numpy/issues/236
