### ISSUE TITLE
Problem loading missing files

### ISSUE THREAD

**Issue by guillaume-heusch** [bioidiap/bob.io.base#13]
Hi Guys,

I'm having some troubles to "catch" errors when trying to load files that don't exist. Here's the code I'm using - and it was working fine until last week:

```python
try:
      color = bob.io.base.load(illum_file)
      except (IOError, RuntimeError) as e:
        logger.warn("Skipping file `%s' (no color signals file available)",  obj.stem)
        continue
```
Now when I'm running it, I get this error:

terminate called after throwing an instance of 'std::runtime_error'
  what():  cannot open file `bla-bla-bla.hdf5'
Aborted

Of course, I'm able to correct that by a simple test using os.path.isfile(), but I'm wondering what's going on here.

Thanks
Guillaume

**Comment by anjos** [comment]
How are you bootstrapping?

**Comment by guillaume-heusch** [comment]
Using the system's python ... I'll try using the one in bob-stable and I'll let you know !

**Comment by guillaume-heusch** [comment]
Still not working ... neither with system's python, nor with bob-stable python - and also not working when bootstrapping with the previous bob-stable version (from 09/05)

**Comment by anjos** [comment]
Very strange. Let's take it up this pm.

**Comment by tiagofrepereira2012** [comment]
Weird, I didn't manage to reproduce it.
Basically I tried to open the file `xuxu.hdf5` (this one does not exist)

```
import bob.io.base

illum_file = "xuxu.hdf5"
try:
  color = bob.io.base.load(illum_file)
except (IOError, RuntimeError) as e:
  print e
```

And I have the expected behaviour

`File - xuxu.hdf5: C++ exception caught: 'cannot open file `xuxu.hdf5''`

**Comment by anjos** [comment]
Have you recently setup matlab (or used any SETSHELL) that may affect your runtime environment? These problems are typically created by environment modifications or sorts.

**Comment by anjos** [comment]
Fixed now using an homogeneous build.
