### ISSUE TITLE
Bob nightlies are failling

### ISSUE THREAD

**Issue by tiagofrepereira2012** [bioidiap/bob.io.base#9]
As you can see here, our nightlies is broken (just one example).
   https://gitlab.idiap.ch/biometric/bob.nightlies/builds/2355

Follow bellow a short example on how to reproduce the error
```
import numpy
from bob.io.base import File

a3 = numpy.random.normal(size=(3,4)).astype('complex128') #not supported
File("xuxu.bindata",'w').write(a3)
```

Debugging a bit (With André's help), I found that a runtime error is raised here (https://github.com/bioidiap/bob.io.base/blob/master/bob/io/base/file.cpp#L412) and we have a catch here (https://github.com/bioidiap/bob.io.base/blob/master/bob/io/base/file.cpp#L415) ready to catch the std::runtime_error, but for some reason this macro is not working (the macro is defined at this point of the code).

If you explicitly set do try{}catch(...){} in (https://github.com/bioidiap/bob.io.base/blob/master/bob/io/base/file.cpp#L412) and raise a PyExc_RuntimeError (which is exactly the macro does) the code just work nice.

I don't know what is going on here.

**Comment by 183amir** [comment]
Hey @tiagofrepereira2012, I noticed that in (https://github.com/bioidiap/bob.extension/blob/master/bob/extension/include/bob.extension/defines.h#L36) if `BOB_DEBUG` is defined, exceptions are not caught anymore. Building `bob.io.base` in non-debug mode fixes this issue.
I do not know how it was working before but if you change `debug` to `false` in `buildout.cfg`, all tests will pass correctly.

**Comment by tiagofrepereira2012** [comment]
Hey,

This was a recent update from @siebenkopf  (https://github.com/bioidiap/bob.extension/issues/8).
Completely forgot it.

I set the flag debug=false in the .gitlab-ci.yml for each environment.

Will close this one.
